.TH "Core/Source/Startup/Window Directory Reference" 3 "Tue Mar 20 2018" "Project: Pyro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Source/Startup/Window Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBWindowManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBWindowManager\&.h\fP"
.br
.in -1c
