.TH "Core/Source/Startup Directory Reference" 3 "Tue Mar 20 2018" "Project: Pyro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Source/Startup Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBWindow\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCore\&.cpp\fP"
.br
.ti -1c
.RI "file \fBstdafx\&.cpp\fP"
.br
.ti -1c
.RI "file \fBstdafx\&.h\fP"
.br
.ti -1c
.RI "file \fBtargetver\&.h\fP"
.br
.in -1c
