.TH "Core/Source/Startup/Core.cpp" 3 "Tue Mar 20 2018" "Project: Pyro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Source/Startup/Core.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'Window/WindowManager\&.h'\fP
.br
\fC#include '\&.\&./Engine/Graphics/Meshes/Mesh\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "
.PP
 "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP

.PP
 
.SS ""
.PP
Main entry-point for this application\&. 
.PP
.SS "Exit-code for the process - 0 for success, else an error code\&.  "

.PP
Definition at line 17 of file Core\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Project: Pyro from the source code\&.
