.TH "Mesh" 3 "Tue Mar 20 2018" "Project: Pyro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mesh \- 
.PP
  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mesh\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMesh\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fB~Mesh\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBInit\fP (void)"
.br
.RI "Initializes this object\&. "
.ti -1c
.RI "GLuint \fBGetVAO\fP (void)"
.br
.RI "Gets the vao\&. "
.ti -1c
.RI "GLuint \fBGetBuffers\fP (void)"
.br
.RI "Gets the buffers\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
 


.PP
 
.PP
A mesh\&. 
.PP
Definition at line 10 of file Mesh\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Mesh::Mesh ()"

.PP
Default constructor\&. 
.PP
.PP
.PP
 
.PP
Default constructor\&. 
.PP
Definition at line 11 of file Mesh\&.cpp\&.
.SS "Mesh::~Mesh ()"

.PP
Destructor\&. 
.PP
Definition at line 17 of file Mesh\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "GLuint Mesh::GetBuffers (void)"

.PP
Gets the buffers\&. 
.PP
.PP
.SS "The buffers\&.  "

.PP
Definition at line 60 of file Mesh\&.cpp\&.
.SS "GLuint Mesh::GetVAO (void)"

.PP
Gets the vao\&. 
.PP
.PP
.SS "The vao\&.  "

.PP
Definition at line 49 of file Mesh\&.cpp\&.
.SS "void Mesh::Init (void)"

.PP
Initializes this object\&. 
.PP
Definition at line 22 of file Mesh\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Project: Pyro from the source code\&.
