.TH "Core/Source/Startup/stdafx.h" 3 "Tue Mar 20 2018" "Project: Pyro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Source/Startup/stdafx.h
.SH SYNOPSIS
.br
.PP
\fC#include 'targetver\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <tchar\&.h>\fP
.br
\fC#include <glew\&.h>\fP
.br
\fC#include <glfw3\&.h>\fP
.br
\fC#include <glm/glm\&.hpp>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Project: Pyro from the source code\&.
