.TH "Core/Source/Startup/Window/WindowManager.h" 3 "Tue Mar 20 2018" "Project: Pyro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Source/Startup/Window/WindowManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindowManager\fP"
.br
.RI "
.PP
 "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Project: Pyro from the source code\&.
