.TH "Core/Source/Startup/Window/WindowManager.cpp" 3 "Tue Mar 20 2018" "Project: Pyro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Source/Startup/Window/WindowManager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdafx\&.h>\fP
.br
\fC#include 'WindowManager\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Project: Pyro from the source code\&.
